### ISSUE TITLE
Managing teachers, students

### ISSUE THREAD

**Issue by JanMSor** [trintel/trintel#80]
There should be a game level admin for managing teacher users, e.g. deleting users or changing other settings, like resetting passwords etc.

This role should also have the possibility to reset passwords for student users.

A current problem is a teacher (Giuseppe) creating his account, including setting the password, and from the start is unable to login (wrong password) even after resetting password several times.

**Comment by b3z** [comment]
Tell him to send me a private email to b3z@zeppel.eu and we will resolve it.

**Comment by b3z** [comment]
This should be better now. We can put other measures in place, if this turns out to be a frequently arising issue in the future.

The reason why users cannot be deleted but only deactivated is because they might still be part of the game. Thus, deleting them would lead to inconsistent transactions.

Every user can reset their own password. That's why there is no extra user administration. Furthermore, we actively decided against it in an earlier stage of development together with @Bennideluecks. 

Lastly, what settings would you like to change? As far as I am concerned, all existing settings can be set by an admin. 

I am going to close this for now. Feel free to reopen if questions arise.
